name: simple_dart_checkbox_list
description: Checkbox List Component
version: 0.0.2
repository: https://github.com/simple-dart/chackbox_list
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'


dependencies:
  simple_dart_ui_core: ^0.0.6

